version: '3.4'

services:
  mariadb:
    image: mariadb:10.1.32
    container_name: my-mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=168168168kmg
      - MYSQL_ROOT_PASSWORD=168168168kmg
    ports:
      - '3306:3306'
    volumes:
      - ./mariadb:/var/lib/mysql
    
  management_mariadb:
    image: phpmyadmin/phpmyadmin
    container_name: my-management-mariadb
    environment:
      PMA_HOST: mariadb
    links:
      - mariadb:database
    ports:
      - '8081:80'
  
  mysql:
    image: mysql:5.7.37
    container_name: my-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=my_root
      - MYSQL_PASSWORD=my_pass
      - MYSQL_ROOT_PASSWORD=my_pass
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  management_mysql:
    image: phpmyadmin/phpmyadmin
    container_name: my-management-mysql
    environment:
      PMA_HOST: mysql
    links:
      - mysql:database
    ports:
      - '8082:80'