version: '3.4'

services:
  mysql:
    image: mysql:5.7.37
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_USER=my_root
      - MYSQL_PASSWORD=my_pass
      - MYSQL_ROOT_PASSWORD=my_pass
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql 

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: my-app
    restart: always
    ports:
      - '3030:3030'
    depends_on:
      - mysql
    tdin_open: true
    tty: true